### ISSUE TITLE
Game crashes when scrolling through Freeplay with the Mouse Wheel too quickly

### ISSUE THREAD

**Issue by Tattleamelia** [mikolka9144/P-Slice#11]
### Describe your bug here.

was just messing around on freeplay after beating a song and the game just abruptly crashed while i was using my mouse wheel to scroll quickly
![image](https://github.com/user-attachments/assets/1b22f822-f784-4b2a-acdd-a8be85e47a4f)

### Are you modding a build from source or with Lua?

No modding

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Base mod, nothing was changed.

**Comment by mikolka9144** [comment]
Can you provide the logs for this crash?

**Comment by Tattleamelia** [comment]
can't unfortunately. it was a not responding crash as seen in the screenshot rather than a haxe crash, so it didn't generate a crash log file
i suppose that'd be more of a freeze than a crash but i use those two interchangeably so i'm not too sure

**Comment by mikolka9144** [comment]
I was not able to reproduce this bug. Feel free to reopen this issue if it persists in 1.1 (and please give logs/crash report)
