### ISSUE TITLE
Freeplay Doesn't Work Correctly

### ISSUE THREAD

**Issue by insertnameuserhere** [mikolka9144/P-Slice#12]
### Describe your bug here.

https://github.com/user-attachments/assets/e4a186b3-bb88-4845-9f99-1dc89257104f
its a softlock

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by insertnameuserhere** [comment]
@mikolka9144

**Comment by mikolka9144** [comment]
Outdated build.
Also it seems like there's the issue with Freeplay keybings, which 1.0.2 tries to fix
