### ISSUE TITLE
freeplay goes crazy (1.0.2 BTW)

### ISSUE THREAD

**Issue by ShadowSonic47** [mikolka9144/P-Slice#16]
### Describe your bug here.

i've seen in this issue reporter that the mod fixed the problem with freeplay in 1.0.2, but that is completely wrong, like you're seeing in this video i recorded in 20 seconds
https://drive.google.com/file/d/1YvTXMhbVLx5nZ5_KdSlcOYaw7WM4LJ2H/view?usp=sharing
i hope you can fix it properly

### Are you modding a build from source or with Lua?

No modding

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i didn't edit anything

**Comment by mikolka9144** [comment]
I hate this bug!

Can you maybe send your saves for P-slice? (Just send me %appdata%/mikolka9144 folder)

**Comment by mikolka9144** [comment]
I need to get to the root of this bug

**Comment by mikolka9144** [comment]
I FOUND THE ISSUE! It's in the a gamepad control scheme!

**Comment by mikolka9144** [comment]
Fixed in the re-uploaded 1.0.2
