### ISSUE TITLE
screenshot spam

### ISSUE THREAD

**Issue by NotTama** [mikolka9144/P-Slice#2]
### Describe your bug here.

keeps taking screenshots when i open it, i just downloaded it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mikolka9144** [comment]
Try rebinding a key for screenshoting

Also I would appreciate if you could send game's log

**Comment by NotTama** [comment]
i cant rebind the key, when i open the game it just starts screenshotting

**Comment by mikolka9144** [comment]
Then try to disconnect all keyboards from your computer and tell if the bug still persists

**Comment by NotTama** [comment]
still doing the glitch. But i just realized that starts to slow down after awhile

**Comment by mikolka9144** [comment]
I still suspect an issue with your system, but I'll try to implement a cool down for screenshoting in 1.0.1 update

**Comment by NotTama** [comment]
nvm i just restarted my laptop and it was fine, sorry for the trouble

**Comment by NotTama** [comment]
nvm its still doing the thing

**Comment by NotTama** [comment]
you know what i give up, imma just to this tomorrow
