### ISSUE TITLE
freeplay

### ISSUE THREAD

**Issue by NotTama** [mikolka9144/P-Slice#20]
### Describe your bug here.

it just crashes when i try to open freeplay, its either that its a bug or my laptop just sucks

### Command Prompt/Terminal logs (required)

```bash
nope
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nop

**Comment by mikolka9144** [comment]
Without the logs, there's very little I can do about it (hence why they're required)
