### ISSUE TITLE
Song preview in freeplay bug

### ISSUE THREAD

**Issue by ItzKony** [mikolka9144/P-Slice#22]
### Describe your bug here.

When I put mods (like whitty, tricky, weekend 1 mod, or just i rename the base game mod folder), the song preview is not working. It does that with source code. I tried without using the source code, and the song preview is working. But not with source code.

### Command Prompt/Terminal logs ()

```bash
source/states/freeplay/FreeplayState.hx:2014: Internal failure loading instrumentals for Faucet (HQ) "mods/whitty/songs/faucet-(hq)/Inst.ogg"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only the MainMenuState.hx but I dont think that it is the problem.

**Comment by mikolka9144** [comment]
Because you modified this engine with source: can you send me the exact list of libraries you compiled it with? (The one from "haxelib list")

**Comment by ItzKony** [comment]
Yes sure!

actuate: [1.9.0]
box2d: [1.2.3]
discord_rpc: [git]
flixel-addons: 3.2.2 [3.2.3]
flixel-demos: 3.1.0 [3.2.0]
flixel-templates: 2.6.6 [2.7.0]
flixel-tools: [1.5.1]
flixel-ui: 2.6.0 [2.6.1]
flixel: 5.6.2 [5.8.0]
flxanimate: [git]
FlxPartialSound: [git]
hscript: [2.5.0]
hxCodec: [3.0.2]
hxcpp: [4.3.2]
hxdiscord_rpc: [git]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: 8.1.2 [8.1.3]
linc_luajit: [git]
newgrounds: [2.0.2]
openfl-samples: [8.7.0]
openfl: 9.3.3 [9.3.4]
polymod: [git]
SScript: 8.1.6 10.0.618 [17.2.618]
systools: [1.1.0]
thx.semver: [0.2.2]
tjson: [1.4.0]

**Comment by ItzKony** [comment]
idk if it was what u are asking for ://

**Comment by mikolka9144** [comment]
You have incorrect haxe libraries defined. Information about correct libs are located both in hmm.json and setup scripts

**Comment by ItzKony** [comment]
Oh okay

**Comment by ItzKony** [comment]
Okay so I tried to setup again, and it worked. Tysm for your help!
