### ISSUE TITLE
Single Difficulty

### ISSUE THREAD

**Issue by Blocks-Games** [mikolka9144/P-Slice#23]
### Describe your bug here.

Im making a mod and everytime I open freeplay the difficulty is always set to normal instead of the 1 difficulty

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I first only tried adding the difficulty with 1 chart with the same difficulty. But that didnt work. But yes

**Comment by mikolka9144** [comment]
Works as intended

There could be a feature in the future, where the game would remove empty difficulties, but for now, I don't have that in plans.
