### ISSUE TITLE
Screenshot spam when starting up the game

### ISSUE THREAD

**Issue by insertnameuserhere** [mikolka9144/P-Slice#3]
### Describe your bug here.

https://github.com/user-attachments/assets/cc234a61-3c8f-4664-a01f-c1e5482133bf

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by insertnameuserhere** [comment]
![image](https://github.com/user-attachments/assets/96b8ed49-6a9e-45e2-b830-1d61696800c0)

**Comment by insertnameuserhere** [comment]
no

**Comment by mikolka9144** [comment]
For anyone struggling with this issue I recommend applying this patch. It'll change the game's save location, which hopefully should resolve this issue.
[patch.zip](https://github.com/user-attachments/files/16616693/patch.zip)

I'll integrate them once 1.0.1 gets released

**Comment by insertnameuserhere** [comment]
it fixed nothing
https://github.com/user-attachments/assets/86662eab-ff3b-4f33-bed9-c3c876797896

**Comment by mikolka9144** [comment]
@insertnameuserhere can you confirm if that bug is present on 1.0.1?

**Comment by insertnameuserhere** [comment]
its no longer a spam but it is playable now
https://github.com/user-attachments/assets/fbe1a80f-05ce-4c51-b5e4-22663117cedb

**Comment by ShadowSonic47** [comment]
have you tried to give that option an input key?? sometimes haxe automaticly execute any function of the code when it doesn't have an input to order it to

**Comment by mikolka9144** [comment]
Fixed in re-uploaded 1.0.2
