### ISSUE TITLE
Erect Remixes Charts

### ISSUE THREAD

**Issue by Nicore55** [mikolka9144/P-Slice#30]
### Describe your bug here.

Erect remixes doesn´t seem to have most of their correct chart, so this should be added in real 1.2

### Are you modding a build from source or with Lua?

No modding

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by mikolka9144** [comment]
fixed erect remixes in the full release of 1.2
