### ISSUE TITLE
Tried compiling but got this error

### ISSUE THREAD

**Issue by Vixencool** [mikolka9144/P-Slice#32]
### Describe your bug here.

i downloaded the 0.6.3 version of p-slice engine source code and I got this error when I tried to compile it

### Command Prompt/Terminal logs ()

```bash
Error: Could not find haxelib "FlxPartialSound", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

did nothing

**Comment by mikolka9144** [comment]
You didn't properly install libraries. There are scripts in the "setup" folder that can install required dependencies for you.

**Comment by Vixencool** [comment]
me just being a dumbass ig

**Comment by Vixencool** [comment]
> You didn't properly install libraries. There are scripts in the "setup" folder that can install required dependencies for you.

now this error: source/states/results/ResultState.hx:372: characters 9-13 : Expected expression

**Comment by mikolka9144** [comment]
What haxe version did you use?

**Comment by Vixencool** [comment]
> What haxe version did you use?

4.2.5

**Comment by mikolka9144** [comment]
Use 4.3.5 

> > What haxe version did you use?
> 
> 4.2.5
Use 4.3.5
