### ISSUE TITLE
No Dialouge

### ISSUE THREAD

**Issue by Blocks-Games** [mikolka9144/P-Slice#33]
### Describe your bug here.

I was trying to put dialouge into my week but it wasn't loading. Idk if its me or not.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by mikolka9144** [comment]
Too vague. Make sure that this dialogue works in the vanilla psych
