### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by NotrutoVpn** [mikolka9144/P-Slice#34]
### Describe your bug here.

When I enter the engine, the game crashes and a warning appears "there is no asset library with an ID of default"

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by NotrutoVpn** [comment]
![Captura de tela 2024-09-13 125137](https://github.com/user-attachments/assets/0c3d4fb9-f43f-4205-85f1-403b9146ff3c)

**Comment by NotrutoVpn** [comment]
I installed the updated version, p-slice-1.2-1.0-pre-win.

**Comment by mikolka9144** [comment]
Looks like you did not properly copy "manifest" folder

**Comment by NotrutoVpn** [comment]
ok I'll try again
