### ISSUE TITLE
I perfected a song and the game crashed

### ISSUE THREAD

**Issue by SillyOurple** [mikolka9144/P-Slice#4]
### Describe your bug here.

I was playing the song "Stress" and i got perfect rank, and it crashed my game, help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mikolka9144** [comment]
Can you provide a log? (or at least crash report)

**Comment by SillyOurple** [comment]
cant, for some reason it fixed itself after the crash
