### ISSUE TITLE
Cursor Hidden In Debug Menus

### ISSUE THREAD

**Issue by Pheeoomix** [mikolka9144/P-Slice#5]
### Describe your bug here.

Noticed that my cursor was hidden when in week editor

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mikolka9144** [comment]
Is there any consistent way to reproduce this bug?

**Comment by Pheeoomix** [comment]
it happens when you restart the game by toggling or moving a mod that restarts the game

**Comment by mikolka9144** [comment]
Now I see.. I'll get that fixed in one of the next updates.

**Comment by mikolka9144** [comment]
Fixed in 1.1
