### ISSUE TITLE
Modded weeks cause game to crash

### ISSUE THREAD

**Issue by 420Aether69** [mikolka9144/P-Slice#6]
### Describe your bug here.

Self-explanatory

### Command Prompt/Terminal logs (required)

```bash
Nothing was said
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mikolka9144** [comment]
What modded weeks cause a crash?
Also is it on 1.0.1?

**Comment by 420Aether69** [comment]
> What modded weeks cause a crash? Also is it on 1.0.1?

It's on most recent version and pretty much anything. Whenever I enter freeplay it crashes with any modded weeks. I have a weekend 1 port and girls night out

**Comment by mikolka9144** [comment]
Closing this because too little details were given
