### ISSUE TITLE
Screenshot Spam (1.0.1)

### ISSUE THREAD

**Issue by WolfSteelpaw** [mikolka9144/P-Slice#8]
### Describe your bug here.

The bug where screenshots are made in large quantity are still persisting, you have heavily DAMPENED how bad it is, but it is still persistent

### Are you modding a build from source or with Lua?

No modding

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did ABSOLUTELY nothing to my RELEASE HOTFIX BUILD of P-slice

**Comment by WolfSteelpaw** [comment]
I found a workaround, just unbind the button to screenshot

**Comment by WolfSteelpaw** [comment]
the whole engine has problems similar to this, the freeplay menu wont let the player pick a song thanks to the rapid scrolling thing too

**Comment by mikolka9144** [comment]
Can you send the saves? (they should be located in %appdata%/mikolka9144)

**Comment by mikolka9144** [comment]
https://github.com/mikolka9144/P-Slice/issues/3
